coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no

ignore:
  - "test_*.py"
  - "setup.py"
  - "**/__pycache__"
  - ".github"
  - "htmlcov"